#!/bin/bash
# cdev 
##########################################
#  Console dev tools for Sublime editor  #
##########################################

# Environment startup
if [ "$DEV_EDITOR" = "" ]
  then
    DEV_EDITOR="vim"
fi
if [ "$DEV_RESULT_LIMIT" = "" ]
  then
    DEV_RESULT_LIMIT=10
fi
if [ "$CHOTOT_HOME_PATH" = "" ]
  then
    CHOTOT_HOME_PATH="$HOME"
fi
if [ "$DEV_TOOLS_OPEN" = "" ]
  then
    DEV_TOOLS_OPEN=1
fi
# Path overwrite
if [ "$path_php" = "" ]
  then
    path_php='-path "./php/*"'
fi
if [ "$path_conf" = "" ]
  then 
    path_conf='-path "./conf/*"'
fi
if [ "$path_bconf" = "" ]
  then
    path_bconf='-path "./conf/bconf/*"'
fi
if [ "$path_sql" = "" ]
  then
    path_sql='-path "./scripts/db/plsql/*"'
fi
if [ "$path_c" = "" ]
  then
    path_c='-path "./modules/*" -o -path "./platform/*"'  
fi
if [ "$path_templates" = "" ]
  then
    path_templates='-path "./templates/*"' #@todo need to change filter here 
fi
if [ "$path_www" = "" ]
  then
    path_www='-path "./www/*"'
fi
if [ "$path_js" = "" ]
  then
    path_js='-path "./www/js/*"'
fi
if [ "$path_css" = "" ]
  then
    path_css='-path "./www/css/*"'
fi

path_all='\( -path "./modules/*" -o -path "./platform/*" -o -path "./www/*" -o -path "./php/*" -o -path "./scripts/*" -o -path "./modules/*" -o -path "./templates/*" \)'
# corlor vars
lgray='\e[1;30m'; green='\e[0;32m'; blue='\e[0;34m'; brown='\e[0;33m'; red='\e[0;31m';yellow='\e[1;33m';cyan='\e[0;36m';NC='\e[0m' # No Color 
STR_DIR_ERROR="Can not fild php, templates, conf, and scripts folders\n
Please change to project root folder"
STR_VAR_ERROR="Name is too short, try > 2 chars"
STR_SORRY="Not found"
STR_INPUT="Enter result file No. you want to open or q quit: "

showusage() {
  echo -e "${lgray}Chotot Console Dev Tools 1${NC}
  ${cyan}[usage] ${NC}$0 [-u usage of function] [-n name search] [-m method] [-e extension] search_string
          \t+ ${brown}search_string${NC}  string to search in extension:php method:function
          \t+ ${brown}Broad Match:${NC} *
          \t\t- $0 bre*se #match bresponse
          \t+ ${brown}Options:${NC}
          \t\t- [-n]   ${blue}File name search only${NC}
          \t\t- [-u]  find usage of function
          \t\t+ [-m:]  method search
          \t\t\t- default  ${blue}function & class${NC}
          \t\t\t- ex:  sql, class
          \t\t+ [-e:]  file extension
          \t\t\t- default  ${blue}php${NC}
          \t\t\t- ex:  bconf, sql, php, html,...
          \t\t- ${blue}[-h]${NC}  display this usage information
          \t\t- ${blue}[-l:]${NC}  result limit
          \t${brown}Examples:${NC}
          \t- $0 bresponse
          \t- $0 -u bresponse #find usage of bresponse
          \t- $0 bres #same as bres*
          \t- $0 bre*se #match bresponse
          \t- $0 -o bres #auto open file
          \t- $0 -m class bres #class php
          \t- $0 -e sql accept #SP function name
          \t- $0 -e bconf category #bconf key and value find
          \t${brown}Environment vars:${NC}
          \t- DEV_EDITOR: default $DEV_EDITOR #default dev editor
          \t- CHOTOT_HOME_PATH: default '$HOME' #home path
          \t- DEV_RESULT_LIMIT: default $DEV_RESULT_LIMIT #result limit
          \t- DEV_TOOLS_OPEN: default $DEV_TOOLS_OPEN #auto open
          "
  exit 1
}
set_m=0
set_e=0
# Default var options
method='both'
extension='php'
debug=0
usage=0
file_name=0
usage_str='uniq'
# Grep vars
surfix_grep=" "
mid_grep='.*'
nsur_grep='.*'
# Filter
cmd_function="function"
cmd_both="((class|function) .*)"
cmd_class="class"
cmd_sql="((create|function) .*)"
cmd_templates=""
cmd_conf=""
# Eval bash 3 surfix
sur_=" "
sur_templates=" "
sur_function="("
sur_both="(|{"
sur_class="(|{"
sur_sql="(|{"
sur_conf=".|="
sur_js="{|(|="
# Get options
while getopts :m:e:u:l:dhonu OPTIONS; do
    case $OPTIONS in
        m)
            set_m=1
            method=$OPTARG;;
        e)
            set_e=1
            extension=$OPTARG
            case "$extension" in
              sql)
                if [ $method=='function' ];then #wrong function
                  method='sql'
                fi
              ;;
              *)
                
              ;;
            esac;;
        o) 
            DEV_TOOLS_OPEN=1;;
        n) 
            file_name=1;;
        u)
            usage=1;;
        h)
            showusage
            exit 1;;
        d)
            debug=1;;
        l)
            DEV_RESULT_LIMIT=$OPTARG;;
        ?)
            echo '?'
            showusage
            exit 1;;
        *) 
            echo '*'
            showusage
            exit 1;;
    esac
done
# Show dir error
show_error(){
  echo -e "${red}### "$1" ###${NC}"
}
# Check project root folder
check_root(){
  if [ ! -d "php" ] || [ ! -d "conf" ] || [ ! -d "modules" ] || [ ! -d "templates" ];then
    show_error "$STR_DIR_ERROR"
    exit 1
  fi
}

validate_var(){
  chk_string=$1
  if [ ${#chk_string} -lt 3 ];then
    show_error "$STR_VAR_ERROR"
    exit 1
  fi
}
_debug(){
  if [ "$debug" == 1 ]; then
    echo "method|filter_str: "$filter_str
    echo "mid_grep: "$mid_grep
    echo "filter_folder: "$filter_folder
    echo "usage_str: "$usage_str
    echo "fileExtension: "$fileExtension
    echo "surfix_grep: "$surfix_grep
    echo "functionName: "$functionName
    echo "function DEV_RESULT_LIMIT: "$DEV_RESULT_LIMIT
    echo "CHOTOT_HOME_PATH: "$CHOTOT_HOME_PATH
    echo "DEV_TOOLS_OPEN: "$DEV_TOOLS_OPEN
    exit
  fi
}
main(){

  declare -i ii=0
  line_function_result=''
  fileExtension=$extension;functionName=$1;filter=$method

  if [ $extension == "bconf" ] || [ $extension == "conf" ] ;then
    filter='conf'
  fi

  if [ $extension == "templates" ] || [ $extension == "tmpl" ] || [ $extension == "html" ];then
    fileExtension='tmpl'
  fi

  eval surfix_grep='$sur_'$filter
  if [ $usage -eq 0 ];then
    eval filter_str='$cmd_'$filter
  else
    filter_str=''
    usage_str=" grep -Ev function|class"
  fi

  eval filter_folder='$path_'$fileExtension
  
  # Change file extension, path, other params
  if [ "$file_name" -eq 1  ]; then #seach file name only
    functionName=${functionName//./\*.}; #rep4filename
    fileExtension="-iname '*$functionName*'"
    # All path for name search
    filter_folder=$path_all
    file_result=( $(eval find . $fileExtension $filter_folder | uniq) ) #diff rules
  else #search infile
    fileExtension="-iname '*$fileExtension*'"
    #replace search function name match with *
    functionName=${functionName//\*/.\*}; #rep4func
    if [ "$set_e" -eq 0 ]; then
      filter_folder=$path_all
      fileExtension=" \( -iname '*php*' -o -iname '*tmpl*' -o -iname '*js*' -o -iname '*conf*' \) "
      if [ "$set_m" -eq 0 ]; then
        filter_str=""
        mid_grep=""
      fi
    fi
    file_result=( $(eval find . $fileExtension $filter_folder | xargs grep "$filter_str$mid_grep$functionName$nsur_grep[?$surfix_grep]" -rnisEl | $usage_str | head -n $DEV_RESULT_LIMIT | uniq) )
  fi

  _debug
  
  for FILE in "${file_result[@]}"
  do
     # File list
      echo -e "${cyan}[$ii] ${NC} ${blue}+ $FILE${NC}"
      # Function list
      if [ "$file_name" -eq 0  ]; then
       eval grep --color='always' "\"$filter_str$mid_grep$functionName$nsur_grep[?$surfix_grep]\"" -niE $FILE| $usage_str| while read FUNC 
        do
          echo -e "\t - ${cyan}[$ii]${NC} $FUNC"
        done
      fi
      ((ii = ii+1)) # Num added
  done

  if [ "$file_name" -eq 1  ]; then
    iresult=( $(eval find "." $fileExtension $filter_folder | uniq) )
  else
   iresult=( $(eval find "." $fileExtension $filter_folder | xargs grep "$filter_str$mid_grep$functionName$nsur_grep[?$surfix_grep]" -rniEsl| $usage_str | head -n $DEV_RESULT_LIMIT | uniq) )
  fi
      if [[ "${#iresult[@]}" > 1 ]] # Many result
        then
          echo "$STR_INPUT";read line
          case "$line" in
            "q")
              exit
            ;; 
            *)
              if [ "${iresult["$line"]}" != ""  ]; then
                echo -e "${yellow}[OPEN]${NC} - ${iresult["$line"]}"
                line_function_result=$(eval grep --color='always' "\"$filter_str$mid_grep$functionName$nsur_grep[?$surfix_grep]\"" -niE ${iresult["$line"]}| $usage_str| head -n 1 |cut -f1 -d:)

                if [[ "${DEV_EDITOR}" == "vim" || "${DEV_EDITOR}" == "vi" ]] && [ "$file_name" -eq 0 ]; then
                  exec $DEV_EDITOR +${line_function_result} ${iresult["$line"]}
                else
                  $DEV_EDITOR ${iresult["$line"]}
                fi

              else
                echo -e "${red}$STR_SORRY${NC}"
              fi
            ;;
          esac
      else # One result only
        if [ "${iresult[0]}" != "" ]; then
          if [ "$DEV_TOOLS_OPEN" == 1 ]; then
            echo -e "${yellow}[OPEN]${NC} - ${iresult[0]}"
            # $DEV_EDITOR ${iresult[0]} #open the first result
            line_function_result=$(eval grep --color='always' "\"$filter_str$mid_grep$functionName$nsur_grep[?$surfix_grep]\"" -niE ${iresult["$line"]}| $usage_str| head -n 1 |cut -f1 -d:)
            if [[ "${DEV_EDITOR}" == "vim" || "${DEV_EDITOR}" == "vi" ]] && [ "$file_name" -eq 0 ]; then
              $DEV_EDITOR +$line_function_result ${iresult[0]}
            else
              $DEV_EDITOR ${iresult[0]}
            fi
          fi
        else
          echo -e "${red}$STR_SORRY${NC}"
        fi
      fi
}

if [ $# -lt 1 ]
then
  showusage
fi
check_root
validate_var ${@: -1}
main ${@: -1}